In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
tf.__version__

'2.8.0'

In [3]:
keras.__version__

'2.8.0'

## Building Regression MLP  Using the Sequential API

In [4]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [5]:
housing = fetch_california_housing()

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(housing.data, housing.target)

In [7]:
X_train, X_valid, Y_train, Y_valid = train_test_split(X_train, Y_train)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_valid = scaler.transform(X_valid)
X_test = scaler.transform(X_test)

In [9]:
X_train.shape[1:]

(8,)

### build model

In [10]:
model = keras.models.Sequential()
# model.add(keras.layers.Input(shape=X_train.shape[1:]))
model.add(keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]))
model.add(keras.layers.Dense(1))

2022-04-20 13:37:57.271496: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-20 13:37:57.981694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 278 MB memory:  -> device: 0, name: NVIDIA TITAN RTX, pci bus id: 0000:02:00.0, compute capability: 7.5


In [11]:
# model= keras.models.Sequential([keras.layers.Dense(30, activation="relu", input_shape=X_train.shape[1:]),
#                                keras.layers.Dense(1)])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 30)                270       
                                                                 
 dense_1 (Dense)             (None, 1)                 31        
                                                                 
Total params: 301
Trainable params: 301
Non-trainable params: 0
_________________________________________________________________


### compile the model

In [13]:
model.compile(loss='mean_squared_error', optimizer="sgd")

### train and evaluate

In [15]:
history = model.fit(X_train, Y_train, epochs=20, validation_data=(X_valid, Y_valid))

Epoch 1/20
363/363 [==============================] - 1s 4ms/step - loss: 1.2151 - val_loss: 0.4678
Epoch 2/20
363/363 [==============================] - 1s 3ms/step - loss: 5.9038 - val_loss: 0.9944
Epoch 3/20
363/363 [==============================] - 1s 3ms/step - loss: 0.5064 - val_loss: 0.4171
Epoch 4/20
363/363 [==============================] - 1s 4ms/step - loss: 0.4155 - val_loss: 0.3971
Epoch 5/20
363/363 [==============================] - 1s 3ms/step - loss: 0.3996 - val_loss: 0.3870
Epoch 6/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3908 - val_loss: 0.3794
Epoch 7/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3908 - val_loss: 0.3796
Epoch 8/20
363/363 [==============================] - 1s 3ms/step - loss: 0.3815 - val_loss: 0.3715
Epoch 9/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3850 - val_loss: 0.3688
Epoch 10/20
363/363 [==============================] - 1s 4ms/step - loss: 0.3751 - val_loss: 0.3649

In [16]:
model.evaluate(X_test, Y_test)

162/162 [==============================] - 0s 2ms/step - loss: 0.3542


0.35415133833885193

### predict model

In [17]:
X_new = X_test[:3]

In [18]:
Y_pred = model.predict(X_new)

In [19]:
Y_pred

array([[3.6712413],
       [2.2412815],
       [2.0650868]], dtype=float32)

In [20]:
Y_test[:3]

array([3.638, 2.664, 1.893])

## Save model

In [21]:
model.save("regression_model.h5")

In [22]:
model1 = keras.models.load_model("regression_model.h5")

In [23]:
model1.predict(X_new)

array([[3.6712413],
       [2.2412815],
       [2.0650868]], dtype=float32)

## Callbacks

In [25]:
checkpoint_cb = keras.callbacks.ModelCheckpoint("regression_model.h5")
history = model.fit(X_train, Y_train, epochs=10, callbacks=[checkpoint_cb])

Epoch 1/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3628
Epoch 2/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3597
Epoch 3/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3666
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3584
Epoch 5/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3614
Epoch 6/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3603
Epoch 7/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3588
Epoch 8/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3588
Epoch 9/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3556
Epoch 10/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3566


## save the checkpoint with best metrics on validation data

In [27]:
checkpoint_cb = keras.callbacks.ModelCheckpoint("regression_best_model.h5", save_best_only=True)
history = model.fit(X_train, Y_train, epochs=10, validation_data=(X_valid, Y_valid), callbacks=[checkpoint_cb])

Epoch 1/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3540 - val_loss: 0.3536
Epoch 2/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3538 - val_loss: 0.3475
Epoch 3/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3568 - val_loss: 0.3498
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3561 - val_loss: 0.3460
Epoch 5/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3602 - val_loss: 0.3422
Epoch 6/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3544 - val_loss: 0.3447
Epoch 7/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3532 - val_loss: 0.3806
Epoch 8/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3513 - val_loss: 0.3510
Epoch 9/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3521 - val_loss: 0.3451
Epoch 10/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3554 - val_loss: 0.3409

In [28]:
model2 = keras.models.load_model("regression_best_model.h5")

In [29]:
model2.predict(X_new)

array([[3.760174 ],
       [2.2482715],
       [2.0678287]], dtype=float32)

In [30]:
model1.predict(X_new)

array([[3.6712413],
       [2.2412815],
       [2.0650868]], dtype=float32)

## Early Stopping

In [31]:
early_stop_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)
history = model.fit(X_train, Y_train, epochs=100, validation_data=(X_valid, Y_valid), callbacks=[checkpoint_cb, early_stop_cb])

Epoch 1/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3524 - val_loss: 0.3453
Epoch 2/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3500 - val_loss: 0.3429
Epoch 3/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3493 - val_loss: 0.3382
Epoch 4/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3488 - val_loss: 0.3404
Epoch 5/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3500 - val_loss: 0.3430
Epoch 6/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3472 - val_loss: 0.3418
Epoch 7/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3467 - val_loss: 0.3449
Epoch 8/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3466 - val_loss: 0.3430
Epoch 9/100
363/363 [==============================] - 1s 4ms/step - loss: 0.3486 - val_loss: 0.3423
Epoch 10/100
363/363 [==============================] - 1s 3ms/step - loss: 0.3457 - val_lo

In [35]:
model.predict(X_new)

array([[3.8882475],
       [2.3077078],
       [1.9581234]], dtype=float32)

In [37]:
Y_test[:3]

array([3.638, 2.664, 1.893])

## Tensorboard callback

In [39]:
import os
root_logdir = os.path.join(os.curdir, "tensor_logs")

In [40]:
def get_run_logdir():
    import time
    run_id = time.strftime("run_%Y_%m_%d-%H_%M_%S")
    return os.path.join(root_logdir, run_id)

In [42]:
runlog_dir = get_run_logdir()
print(runlog_dir)

./tensor_logs/run_2022_04_20-16_00_43


In [43]:
tensorboard_cb = keras.callbacks.TensorBoard(runlog_dir)
history = model.fit(X_train, Y_train, epochs=10, validation_data=(X_valid, Y_valid), callbacks=[tensorboard_cb])

Epoch 1/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3272 - val_loss: 0.3194
Epoch 2/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3259 - val_loss: 0.3148
Epoch 3/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3249 - val_loss: 0.3213
Epoch 4/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3250 - val_loss: 0.3177
Epoch 5/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3257 - val_loss: 0.3179
Epoch 6/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3258 - val_loss: 0.3176
Epoch 7/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3283 - val_loss: 0.3161
Epoch 8/10
363/363 [==============================] - 1s 3ms/step - loss: 0.3251 - val_loss: 0.3162
Epoch 9/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3244 - val_loss: 0.3141
Epoch 10/10
363/363 [==============================] - 1s 4ms/step - loss: 0.3241 - val_loss: 0.3122

In [44]:
%load_ext tensorboard

In [45]:
%tensorboard --logdir=./tensor_logs --host=0.0.0.0